---
- name: Fill variables for deploying
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: template_ssh_host
      prompt: "Enter IP of ESXi server "
      private: no
    - name: template_ssh_user
      prompt: "Enter SSH username of ESXi server "
      default: "root"
      private: no
    - name: template_ssh_port
      prompt: "Enter SSH port of ESXi server "
      default: "22"
      private: no
    - name: template_ssh_pass
      prompt: "Enter SSH password of ESXi server "
      private: no
    - name: template_macaddr
      prompt: "Enter MACADDR of ESxi server "
      private: no
    - name: template_ssh_host_vm
      prompt: "Enter IP of Centos/Debian virtual machine: "
      private: no
    - name: template_ssh_user_vm
      prompt: "Enter SSH username of Centos/Debian virtual machine: "
      private: no
    - name: template_ssh_port_vm
      prompt: "Enter SSH port of Centos/Debian virtual machine: "
      private: no
    - name: template_ssh_pass_vm
      prompt: "Enter SSH password of Centos/Debian virtual machine: "
      private: no

  tasks:
    - template: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: '../templates/inventory.j2', dest: '../playbooks/inventory' }
        - { src: '../templates/creds.config.j2', dest: '../creds.config' }
        - { src: '../templates/default.conf.j2', dest: '../nginx/default.conf' }
...